/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns comprehensive system health information including database status, memory usage, and performance metrics.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Metrics
         * @description Returns detailed system metrics including price change statistics, performance data, and database health.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Dashboard Data
         * @description Returns comprehensive dashboard data including overview metrics, price change analytics, and recent activity.
         */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/price-suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Price Suggestion
         * @description Submit a price change suggestion for evaluation against project policies.
         *
         *     **Authentication Required:** HMAC signature in `X-Calibr-Signature` header
         *     **Rate Limit:** 60 requests per minute per project
         */
        post: operations["submitPriceSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Price Changes
         * @description Retrieve a list of price changes for a project with optional filtering.
         */
        get: operations["listPriceChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price-changes/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Price Change
         * @description Approve a pending price change.
         */
        post: operations["approvePriceChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price-changes/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Price Change
         * @description Apply an approved price change to update the actual price.
         */
        post: operations["applyPriceChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/price-changes/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Price Change
         * @description Reject a pending price change.
         */
        post: operations["rejectPriceChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Product Catalog
         * @description Retrieve product catalog information. Can return all products or a specific product by code.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Database
         * @description Seed the database with demo data for testing and development.
         */
        post: operations["seedDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status?: "ok" | "error";
            /** Format: date-time */
            timestamp?: string;
            service?: string;
            version?: string;
            environment?: string;
            /** @description Uptime in seconds */
            uptime?: number;
            /** @description Response time in milliseconds */
            responseTime?: string;
            database?: components["schemas"]["DatabaseHealth"];
            memory?: components["schemas"]["MemoryUsage"];
            system?: components["schemas"]["SystemInfo"];
        };
        DatabaseHealth: {
            /** @enum {string} */
            status?: "healthy" | "unhealthy";
            /** @description Database latency in milliseconds */
            latency?: string;
            /** @description Number of active connections */
            connections?: number;
            /** @description Number of applied migrations */
            migrations?: number;
        };
        MemoryUsage: {
            /** @description Used memory in MB */
            used?: string;
            /** @description Total memory in MB */
            total?: string;
            /** @description External memory in MB */
            external?: string;
        };
        SystemInfo: {
            platform?: string;
            nodeVersion?: string;
            pid?: number;
        };
        MetricsResponse: {
            /** Format: date-time */
            timestamp?: string;
            timeRange?: string;
            responseTime?: string;
            project?: components["schemas"]["ProjectInfo"];
            metrics?: components["schemas"]["MetricsData"];
        };
        ProjectInfo: {
            id?: string;
            name?: string;
            slug?: string;
            tenant?: string;
        };
        MetricsData: {
            priceChanges?: components["schemas"]["PriceChangeMetrics"];
            webhooks?: components["schemas"]["WebhookMetrics"];
            system?: components["schemas"]["SystemMetrics"];
            database?: components["schemas"]["DatabaseMetrics"];
            errors?: components["schemas"]["ErrorMetrics"];
        };
        PriceChangeMetrics: {
            total?: number;
            byStatus?: {
                [key: string]: number;
            };
            bySource?: {
                [key: string]: number;
            };
        };
        WebhookMetrics: {
            total?: number;
            successful?: number;
            failed?: number;
            averageResponseTime?: number;
        };
        SystemMetrics: {
            uptime?: number;
            memory?: {
                used?: number;
                total?: number;
                external?: number;
            };
            cpu?: {
                loadAverage?: number[];
            };
        };
        DatabaseMetrics: {
            connections?: {
                total_connections?: number;
                active_connections?: number;
                idle_connections?: number;
            };
            tableSizes?: {
                schemaname?: string;
                tablename?: string;
                size?: string;
            }[];
        };
        ErrorMetrics: {
            total?: number;
            byType?: {
                [key: string]: number;
            };
            recent?: Record<string, never>[];
        };
        DashboardResponse: {
            /** Format: date-time */
            timestamp?: string;
            timeRange?: string;
            responseTime?: string;
            project?: components["schemas"]["ProjectInfo"];
            dashboard?: components["schemas"]["DashboardData"];
        };
        DashboardData: {
            overview?: components["schemas"]["OverviewMetrics"];
            priceChanges?: components["schemas"]["PriceChangeAnalytics"];
            systemHealth?: components["schemas"]["SystemHealth"];
            recentActivity?: components["schemas"]["ActivityItem"][];
            topProducts?: components["schemas"]["TopProduct"][];
        };
        OverviewMetrics: {
            totalPriceChanges?: number;
            pendingChanges?: number;
            approvedChanges?: number;
            appliedChanges?: number;
            rejectedChanges?: number;
            approvalRate?: number;
            applicationRate?: number;
        };
        PriceChangeAnalytics: {
            hourlyData?: Record<string, never>[];
            bySource?: {
                [key: string]: number;
            };
        };
        SystemHealth: {
            uptime?: number;
            memory?: {
                used?: number;
                total?: number;
                percentage?: number;
            };
            database?: {
                status?: string;
                latency?: number;
            };
            status?: string;
        };
        ActivityItem: {
            id?: string;
            type?: string;
            status?: string;
            source?: string;
            skuCode?: string;
            productName?: string;
            fromAmount?: number;
            toAmount?: number;
            currency?: string;
            /** Format: date-time */
            createdAt?: string;
            context?: Record<string, never>;
        };
        TopProduct: {
            product_name?: string;
            product_code?: string;
            change_count?: number;
            avg_change_amount?: number;
        };
        PriceSuggestionRequest: {
            /**
             * @description SKU code for the product
             * @example PRO-MONTHLY
             */
            skuCode: string;
            /**
             * @description Current price in cents
             * @example 4900
             */
            fromAmount: number;
            /**
             * @description Proposed price in cents
             * @example 5200
             */
            toAmount: number;
            /**
             * @description Currency code
             * @example USD
             */
            currency: string;
            /**
             * @description Source of the price suggestion
             * @example MANUAL
             * @enum {string}
             */
            source: "MANUAL" | "ai-optimizer" | "competitor-monitor" | "system";
            /**
             * @description Unique key to prevent duplicate processing
             * @example suggestion-123
             */
            idempotencyKey: string;
            /** @description Additional context for the price suggestion */
            context?: {
                [key: string]: unknown;
            };
        };
        PriceSuggestionResponse: {
            /** @description Price change ID */
            id?: string;
            /**
             * @description Status of the price change
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "APPLIED" | "REJECTED" | "FAILED";
            policyResult?: components["schemas"]["PolicyResult"];
        };
        PolicyResult: {
            /** @description Whether the policy evaluation passed */
            ok?: boolean;
            checks?: components["schemas"]["PolicyCheck"][];
        };
        PolicyCheck: {
            ok?: boolean;
            name?: string;
            limit?: number;
            deltaPct?: number;
            floor?: number;
            ceiling?: number;
            proposedAmount?: number;
        };
        PriceChangesListResponse: {
            items?: components["schemas"]["PriceChange"][];
        };
        PriceChange: {
            id?: string;
            tenantId?: string;
            projectId?: string;
            skuId?: string;
            source?: string;
            fromAmount?: number;
            toAmount?: number;
            currency?: string;
            context?: Record<string, never>;
            /** @enum {string} */
            status?: "PENDING" | "APPROVED" | "APPLIED" | "REJECTED" | "FAILED" | "ROLLED_BACK";
            policyResult?: components["schemas"]["PolicyResult"];
            approvedBy?: string | null;
            /** Format: date-time */
            appliedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        CatalogListResponse: {
            products?: components["schemas"]["CatalogProduct"][];
        };
        CatalogSingleResponse: {
            product?: components["schemas"]["ProductInfo"];
            skus?: components["schemas"]["SKUInfo"][];
        };
        CatalogProduct: {
            product?: components["schemas"]["ProductInfo"];
            skus?: components["schemas"]["SKUInfo"][];
        };
        ProductInfo: {
            code?: string;
            name?: string;
        };
        SKUInfo: {
            code?: string;
            prices?: components["schemas"]["PriceInfo"][];
        };
        PriceInfo: {
            currency?: string;
            amount?: number;
        };
        ActionResponse: {
            success?: boolean;
            message?: string;
        };
        ApplyResponse: {
            priceId?: string;
            amount?: number;
        };
        SeedResponse: {
            success?: boolean;
            message?: string;
            tenant?: string;
            project?: string;
            products?: string[];
        };
        ErrorResponse: {
            error?: string;
            message?: string | null;
        };
        RateLimitError: {
            error?: string;
            message?: string;
            retryAfter?: number;
            limit?: number;
            remaining?: number;
            resetTime?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description System is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: {
                /** @description Project slug to filter metrics */
                project?: string;
                /** @description Time range for metrics */
                timeRange?: "1h" | "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: {
                /** @description Project slug to filter dashboard data */
                project?: string;
                /** @description Time range for dashboard data */
                timeRange?: "1h" | "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
    submitPriceSuggestion: {
        parameters: {
            query?: never;
            header: {
                /** @description Project identifier */
                "X-Calibr-Project": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceSuggestionRequest"];
            };
        };
        responses: {
            /** @description Price suggestion processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSuggestionResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid HMAC signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project, SKU, or price not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitError"];
                };
            };
        };
    };
    listPriceChanges: {
        parameters: {
            query: {
                /** @description Project slug */
                project: string;
                /** @description Filter by price change status */
                status?: "PENDING" | "APPROVED" | "APPLIED" | "REJECTED" | "FAILED" | "ROLLED_BACK";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price changes retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceChangesListResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approvePriceChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Price change ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price change approved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Price change cannot be approved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Price change not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    applyPriceChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Price change ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price change applied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Price change cannot be applied */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Price change not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rejectPriceChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Price change ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price change rejected successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Price change not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query: {
                /** @description Project slug */
                project: string;
                /** @description Specific product code to retrieve */
                productCode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogListResponse"] | components["schemas"]["CatalogSingleResponse"];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    seedDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database seeded successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedResponse"];
                };
            };
        };
    };
}
