FROM node:20-bullseye-slim AS base
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @calibr/site build

EXPOSE 8080
ENV PORT=8080
CMD ["sh","-c","pnpm --filter @calibr/site start -p $PORT"]

