[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["apps/api/**", "packages/**", "Dockerfile"]
# Trigger rebuild - updated at 2025-10-24

[deploy]
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
