[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPaths = ["apps/api/**", "packages/**", "Dockerfile"]

[deploy]
startCommand = "cd apps/api && pnpm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
