import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  const tenant = await prisma.tenant.create({ data: { name: 'DemoCo' } })
  const project = await prisma.project.create({ 
    data: { 
      tenantId: tenant.id, 
      name: 'Demo Project', 
      slug: 'demo',
      updatedAt: new Date()
    } 
  })
  const product = await prisma.product.create({ 
    data: { 
      tenantId: tenant.id, 
      projectId: project.id,
      name: 'Pro Plan', 
      code: 'PRO', 
      status: 'ACTIVE' 
    } 
  })
  const sku = await prisma.sku.create({ 
    data: { 
      productId: product.id, 
      name: 'Pro Monthly', 
      code: 'PRO-M', 
      status: 'ACTIVE', 
      attributes: { term: 'monthly' } 
    } 
  })
  await prisma.price.create({ 
    data: { 
      skuId: sku.id, 
      currency: 'USD', 
      billingCycle: 'monthly', 
      unit: 'seat', 
      amount: 4900, 
      status: 'ACTIVE' 
    } 
  })
  await prisma.policy.create({ 
    data: { 
      tenantId: tenant.id, 
      projectId: project.id,
      autoApply: false, 
      rules: { 
        maxPctDelta: 0.15, 
        dailyChangeBudgetPct: 0.25, 
        floors: { 'PRO-M': 3900 } 
      },
      updatedAt: new Date()
    } 
  })
  // Mock Hash for 'password' generated by bcryptjs
  const passwordHash = '$2a$10$d8eftGdB5F.McYCUphExe.7Zc2nYWSJw2vawue1EORL2E1ubG5fmK'

  await prisma.user.upsert({
    where: { email: 'demo@calibr.lat' },
    update: { passwordHash, tenantId: tenant.id },
    create: {
      email: 'demo@calibr.lat',
      name: 'Demo User',
      role: 'MEMBER',
      tenantId: tenant.id,
      passwordHash
    }
  })

  await prisma.user.upsert({
    where: { email: 'admin@calibr.lat' },
    update: { passwordHash, tenantId: tenant.id },
    create: {
      email: 'admin@calibr.lat',
      name: 'Admin User',
      role: 'ADMIN',
      tenantId: tenant.id,
      passwordHash
    }
  })

  console.log('Seeded DemoCo and Demo Users.')
}

main().finally(() => prisma.$disconnect())
